### ISSUE TITLE
Unsafe script on login page

### ISSUE THREAD

**Issue by Krinkle** [DamianZaremba/cluebotng-report#1]
https://tools.wmflabs.org/cluebot/?page=Create+Account

> Mixed Content: The page at 'https://tools.wmflabs.org/cluebot/?page=Create+Account' was loaded over HTTPS, but requested an insecure script 'http://www.google.com/recaptcha/api/challenge?k=..'. This request has been blocked; the content must be served over HTTPS.

Should use HTTPS.

As a result one can't create an account when using HTTPS.

**Comment by DamianZaremba** [comment]
Was never designed to support https - https support was added to tools later. All urls need changing to be proto-relative. The auth system also needs re-doing once openid is in place for prod.

**Comment by DamianZaremba** [comment]
Should be fixed on master - just deployed to live.
